esphome:
  name: ha-prusa-cam
  friendly_name: ha-prusa-cam

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "RlJh5rxZKQh1AfAn65/PNzUHUrNAAVm/+M9fPpmOf0w="

ota:
  - platform: esphome
    password: "4d19986dda07fc62ffa8b8c44ed5107b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ha-Prusa-Cam Fallback Hotspot"
    password: "1V0RpipjOA4K"

captive_portal:
    